breaking changes: 移除 subtitle 一句網調用（api 已失效) feat: 右下角按鈕增加預覽進度顯示 feat: toc可設置是否顯示預覽進度 fix: 修復 TypeError: require(...) is not a function 的報錯 #1102 improvement: 日期設置相對日期時，文章的日期格式和最新評論的日期格式統一為 年月日